version: '3.3'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'poll'
      MYSQL_USER: 'poll-admin'
      MYSQL_PASSWORD: 'poll-admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - polls-db:/var/lib/mysql
    command: mysqld --innodb-buffer-pool-size=256M
volumes:
  polls-db:
